spring:
  application:
    name: fraudshield-transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fraudshield
    username: user
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

app:
  kafka:
    topic:
      transactions-created: fraudshield.transactions.created

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html