name: FraudShield CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DDL_AUTO: ${{ secrets.DDL_AUTO }}
      FRAUD_MAX_AMOUNT: ${{ secrets.FRAUD_MAX_AMOUNT }}
      TRANSACTION_SERVICE_PORT: ${{ secrets.TRANSACTION_SERVICE_PORT }}
      FRAUD_DETECTION_SERVICE_PORT: ${{ secrets.FRAUD_DETECTION_SERVICE_PORT }}
      ALERT_SERVICE_PORT: ${{ secrets.ALERT_SERVICE_PORT }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: fraudshield
          POSTGRES_USER: user
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      zookeeper:
        image: confluentinc/cp-zookeeper:7.6.0
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-kafka:7.6.0
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        ports:
          - 9092:9092

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U user; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Build, Test & SonarQube Analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dspring.profiles.active=ci \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}